{ pkgs, ... }:

{
  xdg.mimeApps.enable = true;
  xdg.mimeApps.defaultApplications = let
    none = [ "okteta.desktop" ]; #"notify-send \"Could not open MIME type\" abc";
    # archive = "none";
    # book = "pkgs.foliate}/bin/foliate}";
    # hex = "pkgs.okteta}/bin/okteta";
    # image = "pkgs.imv}/bin/imv";
    # music = "pkgs.vlc}/bin/vlc";
    # video = "pkgs.vlc}/bin/vlc";
    archive = none;
    browser = [ "firefox.desktop" ];
    code = [ "codium.desktop" ];
    hex = [ "okteta.desktop" ];
    image = [ "org.xfce.ristretto.desktop" ];
    music = none;
    text = none;
    video = none;
  in {
    # "application/acad" = none; # .dwg
    # "application/arj" = none; # .arj
    # "application/base64" = text; # .mm .mme
    "application/binhex4" = hex; # .hqx
    "application/binhex" = hex; # .hqx
    # "application/book" = none; # .boo .book
    # "application/cdf" = none; # .cdf
    # "application/clariscad" = none; # .ccad
    # "application/commonground" = none; # .dp
    # "application/drafting" = none; # .drw
    # "application/dsptype" = none; # .tsp
    # "application/dxf" = none; # .dxf
    "application/ecmascript" = code; # .js
    # "application/envoy" = none; # .evy
    "application/excel" = [ "calc.desktop" ]; # .xl .xla .xlb .xlc .xld .xlk .xll .xlm .xls .xlt .xlv .xlw
    # "application/fractals" = none; # .fif
    # "application/freeloader" = none; # .frl
    # "application/futuresplash" = none; # .spl
    # "application/gnutar" = archive; # .tgz
    # "application/groupwise" = none; # .vew
    # "application/hlp" = none; # .hlp
    # "application/hta" = none; # .hta
    # "application/i-deas" = none; # .unv
    # "application/iges" = none; # .iges .igs
    # "application/inf" = none; # .inf
    "application/java-byte-code" = hex; # .class
    "application/java" = code; # .class
    "application/javascript" = code; # .js
    # "application/lha" = none; # .lha
    # "application/lzx" = none; # .lzx
    # "application/mac-binary" = none; # .bin
    # "application/macbinary" = none; # .bin
    # "application/mac-binhex40" = none; # .hqx
    # "application/mac-binhex" = none; # .hqx
    # "application/mac-compactpro" = none; # .cpt
    # "application/marc" = none; # .mrc
    # "application/mbedlet" = none; # .mbd
    # "application/mcad" = none; # .mcd
    # "application/mime" = none; # .aps
    "application/mspowerpoint" = [ "impress.desktop" ]; # .pot .pps .ppt .ppz
    "application/msword" = [ "writer.desktop" ]; # .doc .dot .w6w .wiz .word
    # "application/mswrite" = none; # .wri
    # "application/netmc" = none; # .mcp
    # "application/octet-stream" = none; # .a .arc .arj .bin .com .dump .exe .lha .lhx .lzh .lzx .o .psd .saveme .uu .zoo
    # "application/oda" = none; # .oda
    "application/pdf" = browser; # .pdf
    # "application/pkcs10" = none; # .p10
    # "application/pkcs-12" = none; # .p12
    # "application/pkcs7-mime" = none; # .p7c .p7m
    # "application/pkcs7-signature" = none; # .p7s
    # "application/pkcs-crl" = none; # .crl
    # "application/pkix-cert" = none; # .cer .crt
    # "application/pkix-crl" = none; # .crl
    # "application/plain" = none; # .text
    # "application/postscript" = none; # .ai .eps .ps
    "application/powerpoint" = [ "impress.desktop" ]; # .ppt
    # "application/pro_eng" = none; # .part .prt
    # "application/ringing-tones" = none; # .rng
    # "application/rtf" = none; # .rtf .rtx
    # "application/sdp" = none; # .sdp
    # "application/sea" = none; # .sea
    # "application/set" = none; # .set
    # "application/sla" = none; # .stl
    # "application/smil" = none; # .smi .smil
    # "application/solids" = none; # .sol
    # "application/sounder" = none; # .sdr
    # "application/step" = none; # .step .stp
    # "application/streamingmedia" = none; # .ssm
    # "application/toolbook" = none; # .tbk
    # "application/vda" = none; # .vda
    # "application/vnd.fdf" = none; # .fdf
    # "application/vnd.hp-hpgl" = none; # .hgl .hpg .hpgl
    # "application/vnd.hp-pcl" = none; # .pcl
    # "application/vnd.ms-excel" = none; # .xlb .xlc .xll .xlm .xls .xlw
    # "application/vnd.ms-pki.certstore" = none; # .sst
    # "application/vnd.ms-pki.pko" = none; # .pko
    # "application/vnd.ms-pki.seccat" = none; # .cat
    # "application/vnd.ms-pki.stl" = none; # .stl
    # "application/vnd.ms-powerpoint" = none; # .pot .ppa .pps .ppt .pwz
    # "application/vnd.ms-project" = none; # .mpp
    # "application/vnd.nokia.configuration-message" = none; # .ncm
    # "application/vnd.nokia.ringing-tone" = none; # .rng
    # "application/vnd.rn-realmedia" = none; # .rm
    # "application/vnd.rn-realplayer" = none; # .rnx
    # "application/vnd.wap.wmlc" = none; # .wmlc
    # "application/vnd.wap.wmlscriptc" = none; # .wmlsc
    # "application/vnd.xara" = none; # .web
    # "application/vocaltec-media-desc" = none; # .vmd
    # "application/vocaltec-media-file" = none; # .vmf
    # "application/wordperfect6.0" = none; # .w60 .wp5
    # "application/wordperfect6.1" = none; # .w61
    # "application/wordperfect" = none; # .wp .wp5 .wp6 .wpd
    # "application/x-123" = none; # .wk1
    # "application/x-aim" = none; # .aim
    # "application/x-authorware-bin" = none; # .aab
    # "application/x-authorware-map" = none; # .aam
    # "application/x-authorware-seg" = none; # .aas
    # "application/x-bcpio" = none; # .bcpio
    # "application/x-binary" = none; # .bin
    # "application/x-binhex40" = none; # .hqx
    # "application/x-bsh" = none; # .bsh .sh .shar
    # "application/x-bytecode.elisp" = none; # .elc(compiled_elisp)
    # "application/x-bytecode.python" = none; # .pyc
    # "application/x-bzip2" = none; # .boz .bz2
    # "application/x-bzip" = none; # .bz
    # "application/x-cdf" = none; # .cdf
    # "application/x-cdlink" = none; # .vcd
    # "application/x-chat" = none; # .cha .chat
    # "application/x-cmu-raster" = none; # .ras
    # "application/x-cocoa" = none; # .cco
    # "application/x-compactpro" = none; # .cpt
    # "application/x-compressed" = none; # .gz .tgz .z .zip
    # "application/x-compress" = none; # .z
    # "application/x-conference" = none; # .nsc
    # "application/x-cpio" = none; # .cpio
    # "application/x-cpt" = none; # .cpt
    # "application/x-csh" = none; # .csh
    # "application/x-deepv" = none; # .deepv
    # "application/x-director" = none; # .dcr .dir .dxr
    # "application/x-dvi" = none; # .dvi
    # "application/x-elc" = none; # .elc
    # "application/x-envoy" = none; # .env .evy
    # "application/x-esrehber" = none; # .es
    # "application/x-excel" = none; # .xla .xlb .xlc .xld .xlk .xll .xlm .xls .xlt .xlv .xlw
    # "application/x-frame" = none; # .mif
    # "application/x-freelance" = none; # .pre
    # "application/x-gsp" = none; # .gsp
    # "application/x-gss" = none; # .gss
    # "application/x-gtar" = none; # .gtar
    # "application/x-gzip" = none; # .gz .gzip
    # "application/x-hdf" = none; # .hdf
    # "application/x-helpfile" = none; # .help .hlp
    # "application/x-httpd-imap" = none; # .imap
    # "application/x-ima" = none; # .ima
    # "application/x-internett-signup" = none; # .ins
    # "application/x-inventor" = none; # .iv
    # "application/x-ip2" = none; # .ip
    # "application/x-java-class" = none; # .class
    # "application/x-java-commerce" = none; # .jcm
    # "application/x-javascript" = none; # .js
    # "application/x-koan" = none; # .skd .skm .skp .skt
    # "application/x-ksh" = none; # .ksh
    # "application/x-latex" = none; # .latex .ltx
    # "application/x-lha" = none; # .lha
    # "application/x-lisp" = none; # .lsp
    # "application/x-livescreen" = none; # .ivy
    # "application/x-lotusscreencam" = none; # .scm
    # "application/x-lotus" = none; # .wq1
    # "application/x-lzh" = none; # .lzh
    # "application/x-lzx" = none; # .lzx
    # "application/x-macbinary" = none; # .bin
    # "application/x-mac-binhex40" = none; # .hqx
    # "application/x-magic-cap-package-1.0" = none; # .mc$
    # "application/x-mathcad" = none; # .mcd
    # "application/x-meme" = none; # .mm
    # "application/x-midi" = none; # .mid .midi
    # "application/x-mif" = none; # .mif
    # "application/x-mix-transfer" = none; # .nix
    # "application/xml" = none; # .xml
    # "application/x-mplayer2" = none; # .asx
    # "application/x-msexcel" = none; # .xla .xls .xlw
    # "application/x-mspowerpoint" = none; # .ppt
    # "application/x-navi-animation" = none; # .ani
    # "application/x-navidoc" = none; # .nvd
    # "application/x-navimap" = none; # .map
    # "application/x-navistyle" = none; # .stl
    # "application/x-netcdf" = none; # .cdf .nc
    # "application/x-newton-compatible-pkg" = none; # .pkg
    # "application/x-nokia-9000-communicator-add-on-software" = none; # .aos
    # "application/x-omcdatamaker" = none; # .omcd
    # "application/x-omc" = none; # .omc
    # "application/x-omcregerator" = none; # .omcr
    # "application/x-pagemaker" = none; # .pm4 .pm5
    # "application/x-pcl" = none; # .pcl
    # "application/x-pixclscript" = none; # .plx
    # "application/x-pkcs10" = none; # .p10
    # "application/x-pkcs12" = none; # .p12
    # "application/x-pkcs7-certificates" = none; # .spc
    # "application/x-pkcs7-certreqresp" = none; # .p7r
    # "application/x-pkcs7-mime" = none; # .p7c .p7m
    # "application/x-pkcs7-signature" = none; # .p7a
    # "application/x-pointplus" = none; # .css
    # "application/x-portable-anymap" = none; # .pnm
    # "application/x-project" = none; # .mpc .mpt .mpv .mpx
    # "application/x-qpro" = none; # .wb1
    # "application/x-rtf" = none; # .rtf
    # "application/x-sdp" = none; # .sdp
    # "application/x-sea" = none; # .sea
    # "application/x-seelogo" = none; # .sl
    # "application/x-shar" = none; # .sh .shar
    # "application/x-shockwave-flash" = none; # .swf
    # "application/x-sh" = none; # .sh
    # "application/x-sit" = none; # .sit
    # "application/x-sprite" = none; # .spr .sprite
    # "application/x-stuffit" = none; # .sit
    # "application/x-sv4cpio" = none; # .sv4cpio
    # "application/x-sv4crc" = none; # .sv4crc
    # "application/x-tar" = none; # .tar
    # "application/x-tbook" = none; # .sbk .tbk
    # "application/x-tcl" = none; # .tcl
    # "application/x-texinfo" = none; # .texi .texinfo
    # "application/x-tex" = none; # .tex
    # "application/x-troff-man" = none; # .man
    # "application/x-troff-me" = none; # .me
    # "application/x-troff-ms" = none; # .ms
    # "application/x-troff-msvideo" = none; # .avi
    # "application/x-troff" = none; # .roff .t .tr
    # "application/x-ustar" = none; # .ustar
    # "application/x-visio" = none; # .vsd .vst .vsw
    # "application/x-vnd.audioexplosion.mzz" = none; # .mzz
    # "application/x-vnd.ls-xpix" = none; # .xpix
    # "application/x-vrml" = none; # .vrml
    # "application/x-wais-source" = none; # .src .wsrc
    # "application/x-winhelp" = none; # .hlp
    # "application/x-wintalk" = none; # .wtk
    # "application/x-world" = none; # .svr .wrl
    # "application/x-wpwin" = none; # .wpd
    # "application/x-wri" = none; # .wri
    # "application/x-x509-ca-cert" = none; # .cer .crt .der
    # "application/x-x509-user-cert" = none; # .crt
    # "application/x-zip-compressed" = archive; # .zip
    # "application/zip" = archive; # .zip
    # "audio/aiff" = music; # .aif .aifc .aiff
    # "audio/basic" = music; # .au .snd
    # "audio/it" = music; # .it
    # "audio/make" = music; # .funk .my .pfunk
    # "audio/make.my.funk" = music; # .pfunk
    # "audio/midi" = music; # .kar .mid .midi
    # "audio/mid" = music; # .rmi
    # "audio/mod" = music; # .mod
    # "audio/mpeg3" = music; # .mp3
    # "audio/mpeg" = music; # .m2a .mp2 .mpa .mpg .mpga
    # "audio/nspaudio" = music; # .la .lma
    # "audio/s3m" = music; # .s3m
    # "audio/tsp-audio" = music; # .tsi
    # "audio/tsplayer" = music; # .tsp
    # "audio/vnd.qcelp" = music; # .qcp
    # "audio/voc" = music; # .voc
    # "audio/voxware" = music; # .vox
    # "audio/wav" = music; # .wav
    # "audio/x-adpcm" = music; # .snd
    # "audio/x-aiff" = music; # .aif .aifc .aiff
    # "audio/x-au" = music; # .au
    # "audio/x-gsm" = music; # .gsd .gsm
    # "audio/x-jam" = music; # .jam
    # "audio/x-liveaudio" = music; # .lam
    # "audio/x-midi" = music; # .mid .midi
    # "audio/x-mid" = music; # .mid .midi
    # "audio/x-mod" = music; # .mod
    # "audio/x-mpeg-3" = music; # .mp3
    # "audio/x-mpeg" = music; # .mp2
    # "audio/x-mpequrl" = music; # .m3u
    # "audio/xm" = music; # .xm
    # "audio/x-nspaudio" = music; # .la .lma
    # "audio/x-pn-realaudio-plugin" = music; # .ra .rmp .rpm
    # "audio/x-pn-realaudio" = music; # .ra .ram .rm .rmm .rmp
    # "audio/x-psid" = music; # .sid
    # "audio/x-realaudio" = music; # .ra
    # "audio/x-twinvq-plugin" = music; # .vqe .vql
    # "audio/x-twinvq" = music; # .vqf
    # "audio/x-vnd.audioexplosion.mjuicemediafile" = music; # .mjf
    # "audio/x-voc" = music; # .voc
    # "audio/x-wav" = music; # .wav
    # "chemical/x-pdb" = none; # .pdb .xyz
    # "drawing/x-dwf" = none; # .dwf (old)
    "image/bmp" = image; # .bm .bmp
    "image/cmu-raster" = image; # .ras .rast
    "image/fif" = image; # .fif
    "image/florian" = image; # .flo .turbot
    "image/g3fax" = image; # .g3
    "image/gif" = image; # .gif
    "image/ief" = image; # .ief .iefs
    "image/jpeg" = image; # .jfif .jfif-tbnl .jpe .jpeg .jpg
    "image/jutvision" = image; # .jut
    "image/naplps" = image; # .nap .naplps
    "image/pict" = image; # .pic .pict
    "image/pjpeg" = image; # .jfif .jpe .jpeg .jpg
    "image/png" = image; # .png .x-png
    "image/tiff" = image; # .tif .tiff
    "image/vasa" = image; # .mcf
    "image/vnd.dwg" = image; # .dwg .dxf .svf
    "image/vnd.fpx" = image; # .fpx
    "image/vnd.net-fpx" = image; # .fpx
    "image/vnd.rn-realflash" = image; # .rf
    "image/vnd.rn-realpix" = image; # .rp
    "image/vnd.wap.wbmp" = image; # .wbmp
    "image/vnd.xiff" = image; # .xif
    "image/webp" = browser; # .webp
    "image/xbm" = image; # .xbm
    "image/x-cmu-raster" = image; # .ras
    "image/x-dwg" = image; # .dwg .dxf .svf
    "image/x-icon" = image; # .ico
    "image/x-jg" = image; # .art
    "image/x-jps" = image; # .jps
    "image/x-niff" = image; # .nif .niff
    "image/x-pcx" = image; # .pcx
    "image/x-pict" = image; # .pct
    "image/xpm" = image; # .xpm
    "image/x-portable-anymap" = image; # .pnm
    "image/x-portable-bitmap" = image; # .pbm
    "image/x-portable-graymap" = image; # .pgm
    "image/x-portable-greymap" = image; # .pgm
    "image/x-portable-pixmap" = image; # .ppm
    "image/x-quicktime" = image; # .qif .qti .qtif
    "image/x-rgb" = image; # .rgb
    "image/x-tiff" = image; # .tif .tiff
    "image/x-windows-bmp" = image; # .bmp
    "image/x-xbitmap" = image; # .xbm
    "image/x-xbm" = image; # .xbm
    "image/x-xpixmap" = image; # .pm .xpm
    "image/x-xwd" = image; # .xwd
    "image/x-xwindowdump" = image; # .xwd
    # "i-world/i-vrml" = none; # .ivr
    # "message/rfc822" = none; # .mht .mhtml .mime
    # "model/iges" = none; # .iges .igs
    # "model/vnd.dwf" = none; # .dwf
    # "model/vrml" = none; # .vrml .wrl .wrz
    # "model/x-pov" = none; # .pov
    # "multipart/x-gzip" = archive; # .gzip
    # "multipart/x-ustar" = archive; # .ustar
    # "multipart/x-zip" = archive; # .zip
    # "music/crescendo" = music; # .mid .midi
    # "music/x-karaoke" = music; # .kar
    # "paleovu/x-pv" = none; # .pvu
    # "text/asp" = text; # .asp
    "text/css" = code; # .css
    # "text/ecmascript" = text; # .js
    "text/html" = browser; # .acgi .htm .html .htmls .htx .shtml
    "text/javascript" = code; # .js
    "text/markdown" = code; # .md
    # "text/mcf" = text; # .mcf
    "text/pascal" = code; # .pas
    "text/plain" = code; # .c .c++ .cc .com .conf .cxx .def .f .f90 .for .g .h .hh .idc .jav .java .list .log .lst .m .mar .pl .sdml .text .txt
    "text/richtext" = [ "writer.desktop" ]; # .rt .rtf .rtx
    # "text/scriplet" = text; # .wsc
    # "text/sgml" = text; # .sgm .sgml
    "text/tab-separated-values" = code; # .tsv
    # "text/uri-list" = text; # .uni .unis .uri .uris
    # "text/vnd.abc" = text; # .abc
    # "text/vnd.fmi.flexstor" = text; # .flx
    # "text/vnd.rn-realtext" = text; # .rt
    # "text/vnd.wap.wmlscript" = text; # .wmls
    # "text/vnd.wap.wml" = text; # .wml
    # "text/webviewhtml" = text; # .htt
    "text/x-asm" = code; # .asm .s
    # "text/x-audiosoft-intra" = text; # .aip
    "text/x-c" = code; # .c .cc .cpp
    # "text/x-component" = text; # .htc
    # "text/x-fortran" = text; # .f .f77 .f90 .for
    "text/x-h" = code; # .h .hh
    "text/x-java-source" = code; # .jav .java
    # "text/x-la-asf" = text; # .lsx
    # "text/xml" = browser; # .xml
    # "text/x-m" = text; # .m
    # "text/x-pascal" = text; # .p
    # "text/x-script.csh" = text; # .csh
    # "text/x-script.elisp" = text; # .el
    # "text/x-script.guile" = text; # .scm
    # "text/x-script" = text; # .hlb
    # "text/x-script.ksh" = text; # .ksh
    # "text/x-script.lisp" = text; # .lsp
    # "text/x-script.perl-module" = text; # .pm
    # "text/x-script.perl" = text; # .pl
    # "text/x-script.phyton" = text; # .py
    # "text/x-script.rexx" = text; # .rexx
    # "text/x-script.scheme" = text; # .scm
    # "text/x-script.sh" = text; # .sh
    # "text/x-script.tcl" = text; # .tcl
    # "text/x-script.tcsh" = text; # .tcsh
    # "text/x-script.zsh" = text; # .zsh
    # "text/x-server-parsed-html" = text; # .shtml .ssi
    # "text/x-setext" = text; # .etx
    # "text/x-sgml" = text; # .sgm .sgml
    # "text/x-speech" = text; # .spc .talk
    # "text/x-uil" = text; # .uil
    "text/x-uuencode" = text; # .uu .uue
    # "text/x-vcalendar" = text; # .vcs
    # "video/animaflex" = video; # .afl
    # "video/avi" = video; # .avi
    # "video/avs-video" = video; # .avs
    # "video/dl" = video; # .dl
    # "video/fli" = video; # .fli
    # "video/gl" = video; # .gl
    # "video/mpeg" = video; # .m1v .m2v .mp2 .mp3 .mpa .mpe .mpeg .mpg
    # "video/msvideo" = video; # .avi
    # "video/quicktime" = video; # .moov .mov .qt
    # "video/vdo" = video; # .vdo
    # "video/vivo" = video; # .viv .vivo
    # "video/vnd.rn-realvideo" = video; # .rv
    # "video/vnd.vivo" = video; # .viv .vivo
    # "video/vosaic" = video; # .vos
    # "video/x-amt-demorun" = video; # .xdr
    # "video/x-amt-showrun" = video; # .xsr
    # "video/x-atomic3d-feature" = video; # .fmf
    # "video/x-dl" = video; # .dl
    # "video/x-dv" = video; # .dif .dv
    # "video/x-fli" = video; # .fli
    # "video/x-gl" = video; # .gl
    # "video/x-isvideo" = video; # .isu
    # "video/x-motion-jpeg" = video; # .mjpg
    # "video/x-mpeg" = video; # .mp2 .mp3
    # "video/x-mpeq2a" = video; # .mp2
    # "video/x-ms-asf" = video; # .asf .asx
    # "video/x-ms-asf-plugin" = video; # .asx
    # "video/x-msvideo" = video; # .avi
    # "video/x-qtc" = video; # .qtc
    # "video/x-scm" = video; # .scm
    # "video/x-sgi-movie" = video; # .movie .mv
    # "windows/metafile" = video; # .wmf
    # "www/mime" = browser; # .mime
    # "x-conference/x-cooltalk" = none; # .ice
    # "xgl/drawing" = none; # .xgz
    # "xgl/movie" = none; # .xmz
    # "x-music/x-midi" = music; # .mid .midi
    # "x-world/x-3dmf" = none; # .3dm .3dmf .qd3 .qd3d
    # "x-world/x-svr" = none; # .svr
    # "x-world/x-vrml" = none; # .vrml .wrl .wrz
    # "x-world/x-vrt" = none; # .vrt
    "x-scheme-handler/http" = browser;
    "x-scheme-handler/https" = browser;
    "x-scheme-handler/about" = browser;
    "x-scheme-handler/unknown" = browser;
  };
}